<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  min_width,
  max_width,
  minic,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  prob,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  seqfrac,
  strands,
  priors_file,
  reason_for_stopping,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT minic (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT prob (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT seqfrac (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="4.11.1" release="Fri Jan 15 12:51:59 2016 -0800">
<training_set datafile="segment4.fa" length="381">
<alphabet name="DNA" like="dna">
<letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
<letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
<letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
<letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
<letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
<letter id="V" symbol="V" equals="ACG" name="Not T"/>
<letter id="H" symbol="H" equals="ACT" name="Not G"/>
<letter id="D" symbol="D" equals="AGT" name="Not C"/>
<letter id="B" symbol="B" equals="CGT" name="Not A"/>
<letter id="M" symbol="M" equals="AC" name="Amino"/>
<letter id="R" symbol="R" equals="AG" name="Purine"/>
<letter id="W" symbol="W" equals="AT" name="Weak"/>
<letter id="S" symbol="S" equals="CG" name="Strong"/>
<letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
<letter id="K" symbol="K" equals="GT" name="Keto"/>
</alphabet>
<sequence id="sequence_0" name="GRMZM2G000256|GRMZM2G000256_T03" length="50" weight="1.000000" />
<sequence id="sequence_1" name="GRMZM2G005433|GRMZM2G005433_T02" length="50" weight="1.000000" />
<sequence id="sequence_2" name="AC194734.3_FG004|AC194734.3_FGT004" length="50" weight="1.000000" />
<sequence id="sequence_3" name="AC207722.2_FG009|AC207722.2_FGT009" length="50" weight="1.000000" />
<sequence id="sequence_4" name="AC190623.3_FG001|AC190623.3_FGT001" length="50" weight="1.000000" />
<sequence id="sequence_5" name="GRMZM2G005433|GRMZM2G005433_T01" length="50" weight="1.000000" />
<sequence id="sequence_6" name="GRMZM2G005984|GRMZM2G005984_T01" length="50" weight="1.000000" />
<sequence id="sequence_7" name="GRMZM2G006006|GRMZM2G006006_T01" length="50" weight="1.000000" />
<sequence id="sequence_8" name="GRMZM2G003096|GRMZM2G003096_T01" length="50" weight="1.000000" />
<sequence id="sequence_9" name="GRMZM2G002165|GRMZM2G002165_T01" length="50" weight="1.000000" />
<sequence id="sequence_10" name="GRMZM2G005973|GRMZM2G005973_T01" length="50" weight="1.000000" />
<sequence id="sequence_11" name="GRMZM2G003157|GRMZM2G003157_T01" length="50" weight="1.000000" />
<sequence id="sequence_12" name="GRMZM2G007453|GRMZM2G007453_T01" length="50" weight="1.000000" />
<sequence id="sequence_13" name="GRMZM2G001653|GRMZM2G001653_T01" length="50" weight="1.000000" />
<sequence id="sequence_14" name="GRMZM2G000256|GRMZM2G000256_T04" length="50" weight="1.000000" />
<sequence id="sequence_15" name="AC208915.3_FG010|AC208915.3_FGT010" length="50" weight="1.000000" />
<sequence id="sequence_16" name="AC192204.3_FG005|AC192204.3_FGT005" length="50" weight="1.000000" />
<sequence id="sequence_17" name="GRMZM2G000256|GRMZM2G000256_T01" length="50" weight="1.000000" />
<sequence id="sequence_18" name="GRMZM2G000256|GRMZM2G000256_T02" length="50" weight="1.000000" />
<sequence id="sequence_19" name="AC188023.3_FG005|AC188023.3_FGT005" length="50" weight="1.000000" />
<sequence id="sequence_20" name="GRMZM2G014180|GRMZM2G014180_T04" length="50" weight="1.000000" />
<sequence id="sequence_21" name="GRMZM2G016066|GRMZM2G016066_T02" length="50" weight="1.000000" />
<sequence id="sequence_22" name="GRMZM2G010884|GRMZM2G010884_T02" length="50" weight="1.000000" />
<sequence id="sequence_23" name="GRMZM2G008730|GRMZM2G008730_T01" length="50" weight="1.000000" />
<sequence id="sequence_24" name="GRMZM2G012397|GRMZM2G012397_T01" length="50" weight="1.000000" />
<sequence id="sequence_25" name="GRMZM2G011373|GRMZM2G011373_T01" length="50" weight="1.000000" />
<sequence id="sequence_26" name="GRMZM2G016066|GRMZM2G016066_T01" length="50" weight="1.000000" />
<sequence id="sequence_27" name="GRMZM2G007453|GRMZM2G007453_T03" length="50" weight="1.000000" />
<sequence id="sequence_28" name="GRMZM2G008892|GRMZM2G008892_T01" length="50" weight="1.000000" />
<sequence id="sequence_29" name="GRMZM2G007453|GRMZM2G007453_T02" length="50" weight="1.000000" />
<sequence id="sequence_30" name="GRMZM2G009048|GRMZM2G009048_T01" length="50" weight="1.000000" />
<sequence id="sequence_31" name="GRMZM2G010349|GRMZM2G010349_T02" length="50" weight="1.000000" />
<sequence id="sequence_32" name="GRMZM2G015355|GRMZM2G015355_T01" length="50" weight="1.000000" />
<sequence id="sequence_33" name="GRMZM2G015967|GRMZM2G015967_T01" length="50" weight="1.000000" />
<sequence id="sequence_34" name="GRMZM2G007907|GRMZM2G007907_T01" length="50" weight="1.000000" />
<sequence id="sequence_35" name="GRMZM2G010929|GRMZM2G010929_T02" length="50" weight="1.000000" />
<sequence id="sequence_36" name="GRMZM2G010884|GRMZM2G010884_T01" length="50" weight="1.000000" />
<sequence id="sequence_37" name="GRMZM2G013342|GRMZM2G013342_T01" length="50" weight="1.000000" />
<sequence id="sequence_38" name="GRMZM2G007453|GRMZM2G007453_T04" length="50" weight="1.000000" />
<sequence id="sequence_39" name="GRMZM2G030606|GRMZM2G030606_T01" length="50" weight="1.000000" />
<sequence id="sequence_40" name="GRMZM2G038519|GRMZM2G038519_T03" length="50" weight="1.000000" />
<sequence id="sequence_41" name="GRMZM2G016622|GRMZM2G016622_T01" length="50" weight="1.000000" />
<sequence id="sequence_42" name="GRMZM2G033493|GRMZM2G033493_T01" length="50" weight="1.000000" />
<sequence id="sequence_43" name="GRMZM2G026015|GRMZM2G026015_T01" length="50" weight="1.000000" />
<sequence id="sequence_44" name="GRMZM2G043453|GRMZM2G043453_T02" length="50" weight="1.000000" />
<sequence id="sequence_45" name="GRMZM2G039996|GRMZM2G039996_T01" length="50" weight="1.000000" />
<sequence id="sequence_46" name="GRMZM2G038519|GRMZM2G038519_T02" length="50" weight="1.000000" />
<sequence id="sequence_47" name="GRMZM2G033885|GRMZM2G033885_T01" length="50" weight="1.000000" />
<sequence id="sequence_48" name="GRMZM2G033493|GRMZM2G033493_T02" length="50" weight="1.000000" />
<sequence id="sequence_49" name="GRMZM2G016084|GRMZM2G016084_T01" length="50" weight="1.000000" />
<sequence id="sequence_50" name="GRMZM2G016677|GRMZM2G016677_T01" length="50" weight="1.000000" />
<sequence id="sequence_51" name="GRMZM2G039996|GRMZM2G039996_T02" length="50" weight="1.000000" />
<sequence id="sequence_52" name="GRMZM2G025171|GRMZM2G025171_T01" length="50" weight="1.000000" />
<sequence id="sequence_53" name="GRMZM2G026015|GRMZM2G026015_T02" length="50" weight="1.000000" />
<sequence id="sequence_54" name="GRMZM2G021617|GRMZM2G021617_T01" length="50" weight="1.000000" />
<sequence id="sequence_55" name="GRMZM2G018627|GRMZM2G018627_T02" length="50" weight="1.000000" />
<sequence id="sequence_56" name="GRMZM2G036829|GRMZM2G036829_T01" length="50" weight="1.000000" />
<sequence id="sequence_57" name="GRMZM2G027331|GRMZM2G027331_T01" length="50" weight="1.000000" />
<sequence id="sequence_58" name="GRMZM2G038519|GRMZM2G038519_T04" length="50" weight="1.000000" />
<sequence id="sequence_59" name="GRMZM2G038519|GRMZM2G038519_T01" length="50" weight="1.000000" />
<sequence id="sequence_60" name="GRMZM2G025171|GRMZM2G025171_T02" length="50" weight="1.000000" />
<sequence id="sequence_61" name="GRMZM2G031028|GRMZM2G031028_T02" length="50" weight="1.000000" />
<sequence id="sequence_62" name="GRMZM2G036880|GRMZM2G036880_T01" length="50" weight="1.000000" />
<sequence id="sequence_63" name="GRMZM2G021256|GRMZM2G021256_T01" length="50" weight="1.000000" />
<sequence id="sequence_64" name="GRMZM2G039930|GRMZM2G039930_T02" length="50" weight="1.000000" />
<sequence id="sequence_65" name="GRMZM2G018627|GRMZM2G018627_T01" length="50" weight="1.000000" />
<sequence id="sequence_66" name="GRMZM2G030628|GRMZM2G030628_T01" length="50" weight="1.000000" />
<sequence id="sequence_67" name="GRMZM2G032351|GRMZM2G032351_T01" length="50" weight="1.000000" />
<sequence id="sequence_68" name="GRMZM2G017045|GRMZM2G017045_T01" length="50" weight="1.000000" />
<sequence id="sequence_69" name="GRMZM2G026656|GRMZM2G026656_T01" length="50" weight="1.000000" />
<sequence id="sequence_70" name="GRMZM2G026015|GRMZM2G026015_T03" length="50" weight="1.000000" />
<sequence id="sequence_71" name="GRMZM2G021687|GRMZM2G021687_T01" length="50" weight="1.000000" />
<sequence id="sequence_72" name="GRMZM2G033885|GRMZM2G033885_T02" length="50" weight="1.000000" />
<sequence id="sequence_73" name="GRMZM2G026015|GRMZM2G026015_T04" length="50" weight="1.000000" />
<sequence id="sequence_74" name="GRMZM2G025882|GRMZM2G025882_T01" length="50" weight="1.000000" />
<sequence id="sequence_75" name="GRMZM2G016622|GRMZM2G016622_T02" length="50" weight="1.000000" />
<sequence id="sequence_76" name="GRMZM2G026656|GRMZM2G026656_T02" length="50" weight="1.000000" />
<sequence id="sequence_77" name="GRMZM2G032253|GRMZM2G032253_T01" length="50" weight="1.000000" />
<sequence id="sequence_78" name="GRMZM2G043453|GRMZM2G043453_T01" length="50" weight="1.000000" />
<sequence id="sequence_79" name="GRMZM2G034243|GRMZM2G034243_T01" length="50" weight="1.000000" />
<sequence id="sequence_80" name="GRMZM2G017290|GRMZM2G017290_T02" length="50" weight="1.000000" />
<sequence id="sequence_81" name="GRMZM2G017290|GRMZM2G017290_T01" length="50" weight="1.000000" />
<sequence id="sequence_82" name="GRMZM2G038365|GRMZM2G038365_T01" length="50" weight="1.000000" />
<sequence id="sequence_83" name="GRMZM2G025070|GRMZM2G025070_T01" length="50" weight="1.000000" />
<sequence id="sequence_84" name="GRMZM2G043162|GRMZM2G043162_T01" length="50" weight="1.000000" />
<sequence id="sequence_85" name="GRMZM2G042502|GRMZM2G042502_T01" length="50" weight="1.000000" />
<sequence id="sequence_86" name="GRMZM2G033885|GRMZM2G033885_T03" length="50" weight="1.000000" />
<sequence id="sequence_87" name="GRMZM2G024150|GRMZM2G024150_T01" length="50" weight="1.000000" />
<sequence id="sequence_88" name="GRMZM2G047513|GRMZM2G047513_T01" length="50" weight="1.000000" />
<sequence id="sequence_89" name="GRMZM2G077333|GRMZM2G077333_T01" length="50" weight="1.000000" />
<sequence id="sequence_90" name="GRMZM2G071996|GRMZM2G071996_T01" length="50" weight="1.000000" />
<sequence id="sequence_91" name="GRMZM2G098520|GRMZM2G098520_T01" length="50" weight="1.000000" />
<sequence id="sequence_92" name="GRMZM2G059252|GRMZM2G059252_T01" length="50" weight="1.000000" />
<sequence id="sequence_93" name="GRMZM2G095082|GRMZM2G095082_T02" length="50" weight="1.000000" />
<sequence id="sequence_94" name="GRMZM2G092427|GRMZM2G092427_T03" length="50" weight="1.000000" />
<sequence id="sequence_95" name="GRMZM2G083470|GRMZM2G083470_T01" length="50" weight="1.000000" />
<sequence id="sequence_96" name="GRMZM2G087063|GRMZM2G087063_T02" length="50" weight="1.000000" />
<sequence id="sequence_97" name="GRMZM2G059083|GRMZM2G059083_T04" length="50" weight="1.000000" />
<sequence id="sequence_98" name="GRMZM2G085301|GRMZM2G085301_T01" length="50" weight="1.000000" />
<sequence id="sequence_99" name="GRMZM2G068557|GRMZM2G068557_T01" length="50" weight="1.000000" />
<sequence id="sequence_100" name="GRMZM2G087063|GRMZM2G087063_T04" length="50" weight="1.000000" />
<sequence id="sequence_101" name="GRMZM2G058070|GRMZM2G058070_T01" length="50" weight="1.000000" />
<sequence id="sequence_102" name="GRMZM2G047954|GRMZM2G047954_T02" length="50" weight="1.000000" />
<sequence id="sequence_103" name="GRMZM2G078569|GRMZM2G078569_T02" length="50" weight="1.000000" />
<sequence id="sequence_104" name="GRMZM2G086052|GRMZM2G086052_T03" length="50" weight="1.000000" />
<sequence id="sequence_105" name="GRMZM2G051059|GRMZM2G051059_T05" length="50" weight="1.000000" />
<sequence id="sequence_106" name="GRMZM2G059252|GRMZM2G059252_T02" length="50" weight="1.000000" />
<sequence id="sequence_107" name="GRMZM2G078569|GRMZM2G078569_T01" length="50" weight="1.000000" />
<sequence id="sequence_108" name="GRMZM2G063592|GRMZM2G063592_T01" length="50" weight="1.000000" />
<sequence id="sequence_109" name="GRMZM2G092174|GRMZM2G092174_T01" length="50" weight="1.000000" />
<sequence id="sequence_110" name="GRMZM2G087063|GRMZM2G087063_T03" length="50" weight="1.000000" />
<sequence id="sequence_111" name="GRMZM2G094978|GRMZM2G094978_T02" length="50" weight="1.000000" />
<sequence id="sequence_112" name="GRMZM2G079759|GRMZM2G079759_T01" length="50" weight="1.000000" />
<sequence id="sequence_113" name="GRMZM2G059151|GRMZM2G059151_T01" length="50" weight="1.000000" />
<sequence id="sequence_114" name="GRMZM2G062788|GRMZM2G062788_T01" length="50" weight="1.000000" />
<sequence id="sequence_115" name="GRMZM2G092427|GRMZM2G092427_T02" length="50" weight="1.000000" />
<sequence id="sequence_116" name="GRMZM2G090271|GRMZM2G090271_T01" length="50" weight="1.000000" />
<sequence id="sequence_117" name="GRMZM2G087598|GRMZM2G087598_T01" length="50" weight="1.000000" />
<sequence id="sequence_118" name="GRMZM2G094224|GRMZM2G094224_T02" length="50" weight="1.000000" />
<sequence id="sequence_119" name="GRMZM2G058447|GRMZM2G058447_T01" length="50" weight="1.000000" />
<sequence id="sequence_120" name="GRMZM2G062044|GRMZM2G062044_T01" length="50" weight="1.000000" />
<sequence id="sequence_121" name="GRMZM2G048313|GRMZM2G048313_T01" length="50" weight="1.000000" />
<sequence id="sequence_122" name="GRMZM2G092427|GRMZM2G092427_T01" length="50" weight="1.000000" />
<sequence id="sequence_123" name="GRMZM2G090112|GRMZM2G090112_T01" length="50" weight="1.000000" />
<sequence id="sequence_124" name="GRMZM2G087590|GRMZM2G087590_T05" length="50" weight="1.000000" />
<sequence id="sequence_125" name="GRMZM2G057281|GRMZM2G057281_T01" length="50" weight="1.000000" />
<sequence id="sequence_126" name="GRMZM2G072280|GRMZM2G072280_T03" length="50" weight="1.000000" />
<sequence id="sequence_127" name="GRMZM2G069569|GRMZM2G069569_T02" length="50" weight="1.000000" />
<sequence id="sequence_128" name="GRMZM2G101617|GRMZM2G101617_T01" length="50" weight="1.000000" />
<sequence id="sequence_129" name="GRMZM2G097283|GRMZM2G097283_T01" length="50" weight="1.000000" />
<sequence id="sequence_130" name="GRMZM2G057281|GRMZM2G057281_T02" length="50" weight="1.000000" />
<sequence id="sequence_131" name="GRMZM2G092311|GRMZM2G092311_T02" length="50" weight="1.000000" />
<sequence id="sequence_132" name="GRMZM2G081462|GRMZM2G081462_T01" length="50" weight="1.000000" />
<sequence id="sequence_133" name="GRMZM2G087590|GRMZM2G087590_T01" length="50" weight="1.000000" />
<sequence id="sequence_134" name="GRMZM2G081462|GRMZM2G081462_T02" length="50" weight="1.000000" />
<sequence id="sequence_135" name="GRMZM2G043500|GRMZM2G043500_T01" length="50" weight="1.000000" />
<sequence id="sequence_136" name="GRMZM2G044247|GRMZM2G044247_T01" length="50" weight="1.000000" />
<sequence id="sequence_137" name="GRMZM2G092311|GRMZM2G092311_T03" length="50" weight="1.000000" />
<sequence id="sequence_138" name="GRMZM2G087598|GRMZM2G087598_T02" length="50" weight="1.000000" />
<sequence id="sequence_139" name="GRMZM2G085646|GRMZM2G085646_T01" length="50" weight="1.000000" />
<sequence id="sequence_140" name="GRMZM2G072280|GRMZM2G072280_T02" length="50" weight="1.000000" />
<sequence id="sequence_141" name="GRMZM2G089147|GRMZM2G089147_T02" length="50" weight="1.000000" />
<sequence id="sequence_142" name="GRMZM2G094224|GRMZM2G094224_T01" length="50" weight="1.000000" />
<sequence id="sequence_143" name="GRMZM2G074393|GRMZM2G074393_T01" length="50" weight="1.000000" />
<sequence id="sequence_144" name="GRMZM2G065461|GRMZM2G065461_T01" length="50" weight="1.000000" />
<sequence id="sequence_145" name="GRMZM2G092311|GRMZM2G092311_T01" length="50" weight="1.000000" />
<sequence id="sequence_146" name="GRMZM2G077436|GRMZM2G077436_T01" length="50" weight="1.000000" />
<sequence id="sequence_147" name="GRMZM2G056424|GRMZM2G056424_T01" length="50" weight="1.000000" />
<sequence id="sequence_148" name="GRMZM2G087041|GRMZM2G087041_T01" length="50" weight="1.000000" />
<sequence id="sequence_149" name="GRMZM2G103101|GRMZM2G103101_T01" length="50" weight="1.000000" />
<sequence id="sequence_150" name="GRMZM2G102838|GRMZM2G102838_T01" length="50" weight="1.000000" />
<sequence id="sequence_151" name="GRMZM2G072280|GRMZM2G072280_T01" length="50" weight="1.000000" />
<sequence id="sequence_152" name="GRMZM2G072174|GRMZM2G072174_T01" length="50" weight="1.000000" />
<sequence id="sequence_153" name="GRMZM2G067883|GRMZM2G067883_T01" length="50" weight="1.000000" />
<sequence id="sequence_154" name="GRMZM2G059083|GRMZM2G059083_T01" length="50" weight="1.000000" />
<sequence id="sequence_155" name="GRMZM2G078569|GRMZM2G078569_T04" length="50" weight="1.000000" />
<sequence id="sequence_156" name="GRMZM2G047954|GRMZM2G047954_T01" length="50" weight="1.000000" />
<sequence id="sequence_157" name="GRMZM2G049547|GRMZM2G049547_T03" length="50" weight="1.000000" />
<sequence id="sequence_158" name="GRMZM2G060451|GRMZM2G060451_T01" length="50" weight="1.000000" />
<sequence id="sequence_159" name="GRMZM2G087435|GRMZM2G087435_T01" length="50" weight="1.000000" />
<sequence id="sequence_160" name="GRMZM2G080107|GRMZM2G080107_T01" length="50" weight="1.000000" />
<sequence id="sequence_161" name="GRMZM2G097457|GRMZM2G097457_T02" length="50" weight="1.000000" />
<sequence id="sequence_162" name="GRMZM2G059191|GRMZM2G059191_T01" length="50" weight="1.000000" />
<sequence id="sequence_163" name="GRMZM2G081955|GRMZM2G081955_T01" length="50" weight="1.000000" />
<sequence id="sequence_164" name="GRMZM2G048907|GRMZM2G048907_T01" length="50" weight="1.000000" />
<sequence id="sequence_165" name="GRMZM2G085646|GRMZM2G085646_T02" length="50" weight="1.000000" />
<sequence id="sequence_166" name="GRMZM2G078569|GRMZM2G078569_T03" length="50" weight="1.000000" />
<sequence id="sequence_167" name="GRMZM2G112728|GRMZM2G112728_T01" length="50" weight="1.000000" />
<sequence id="sequence_168" name="GRMZM2G125575|GRMZM2G125575_T01" length="50" weight="1.000000" />
<sequence id="sequence_169" name="GRMZM2G374263|GRMZM2G374263_T01" length="50" weight="1.000000" />
<sequence id="sequence_170" name="GRMZM2G308944|GRMZM2G308944_T01" length="50" weight="1.000000" />
<sequence id="sequence_171" name="GRMZM2G124532|GRMZM2G124532_T02" length="50" weight="1.000000" />
<sequence id="sequence_172" name="GRMZM2G118646|GRMZM2G118646_T01" length="50" weight="1.000000" />
<sequence id="sequence_173" name="GRMZM2G163809|GRMZM2G163809_T02" length="50" weight="1.000000" />
<sequence id="sequence_174" name="GRMZM2G160268|GRMZM2G160268_T02" length="50" weight="1.000000" />
<sequence id="sequence_175" name="GRMZM2G156068|GRMZM2G156068_T01" length="50" weight="1.000000" />
<sequence id="sequence_176" name="GRMZM2G131489|GRMZM2G131489_T01" length="50" weight="1.000000" />
<sequence id="sequence_177" name="GRMZM2G122715|GRMZM2G122715_T02" length="50" weight="1.000000" />
<sequence id="sequence_178" name="GRMZM2G325019|GRMZM2G325019_T01" length="50" weight="1.000000" />
<sequence id="sequence_179" name="GRMZM2G129513|GRMZM2G129513_T01" length="50" weight="1.000000" />
<sequence id="sequence_180" name="GRMZM2G419111|GRMZM2G419111_T01" length="50" weight="1.000000" />
<sequence id="sequence_181" name="GRMZM2G160268|GRMZM2G160268_T04" length="50" weight="1.000000" />
<sequence id="sequence_182" name="GRMZM2G123371|GRMZM2G123371_T02" length="50" weight="1.000000" />
<sequence id="sequence_183" name="GRMZM2G115077|GRMZM2G115077_T01" length="50" weight="1.000000" />
<sequence id="sequence_184" name="GRMZM2G451224|GRMZM2G451224_T01" length="50" weight="1.000000" />
<sequence id="sequence_185" name="GRMZM2G404025|GRMZM2G404025_T01" length="50" weight="1.000000" />
<sequence id="sequence_186" name="GRMZM2G360567|GRMZM2G360567_T01" length="50" weight="1.000000" />
<sequence id="sequence_187" name="GRMZM2G139803|GRMZM2G139803_T01" length="50" weight="1.000000" />
<sequence id="sequence_188" name="GRMZM2G129208|GRMZM2G129208_T01" length="50" weight="1.000000" />
<sequence id="sequence_189" name="GRMZM2G414192|GRMZM2G414192_T01" length="50" weight="1.000000" />
<sequence id="sequence_190" name="GRMZM2G117412|GRMZM2G117412_T03" length="50" weight="1.000000" />
<sequence id="sequence_191" name="GRMZM2G112728|GRMZM2G112728_T03" length="50" weight="1.000000" />
<sequence id="sequence_192" name="GRMZM2G153416|GRMZM2G153416_T01" length="50" weight="1.000000" />
<sequence id="sequence_193" name="GRMZM2G113418|GRMZM2G113418_T01" length="50" weight="1.000000" />
<sequence id="sequence_194" name="GRMZM2G413972|GRMZM2G413972_T01" length="50" weight="1.000000" />
<sequence id="sequence_195" name="GRMZM2G433927|GRMZM2G433927_T01" length="50" weight="1.000000" />
<sequence id="sequence_196" name="GRMZM2G178775|GRMZM2G178775_T01" length="50" weight="1.000000" />
<sequence id="sequence_197" name="GRMZM2G162748|GRMZM2G162748_T01" length="50" weight="1.000000" />
<sequence id="sequence_198" name="GRMZM2G380414|GRMZM2G380414_T01" length="50" weight="1.000000" />
<sequence id="sequence_199" name="GRMZM2G429955|GRMZM2G429955_T01" length="50" weight="1.000000" />
<sequence id="sequence_200" name="GRMZM2G175804|GRMZM2G175804_T01" length="50" weight="1.000000" />
<sequence id="sequence_201" name="GRMZM2G149428|GRMZM2G149428_T02" length="50" weight="1.000000" />
<sequence id="sequence_202" name="GRMZM2G107089|GRMZM2G107089_T01" length="50" weight="1.000000" />
<sequence id="sequence_203" name="GRMZM2G348873|GRMZM2G348873_T01" length="50" weight="1.000000" />
<sequence id="sequence_204" name="GRMZM2G163809|GRMZM2G163809_T04" length="50" weight="1.000000" />
<sequence id="sequence_205" name="GRMZM2G320325|GRMZM2G320325_T02" length="50" weight="1.000000" />
<sequence id="sequence_206" name="GRMZM2G172723|GRMZM2G172723_T04" length="50" weight="1.000000" />
<sequence id="sequence_207" name="GRMZM2G120579|GRMZM2G120579_T01" length="50" weight="1.000000" />
<sequence id="sequence_208" name="GRMZM2G180720|GRMZM2G180720_T01" length="50" weight="1.000000" />
<sequence id="sequence_209" name="GRMZM2G163809|GRMZM2G163809_T06" length="50" weight="1.000000" />
<sequence id="sequence_210" name="GRMZM2G431314|GRMZM2G431314_T01" length="50" weight="1.000000" />
<sequence id="sequence_211" name="GRMZM2G383807|GRMZM2G383807_T01" length="50" weight="1.000000" />
<sequence id="sequence_212" name="GRMZM2G135283|GRMZM2G135283_T04" length="50" weight="1.000000" />
<sequence id="sequence_213" name="GRMZM2G155216|GRMZM2G155216_T02" length="50" weight="1.000000" />
<sequence id="sequence_214" name="GRMZM2G108467|GRMZM2G108467_T01" length="50" weight="1.000000" />
<sequence id="sequence_215" name="GRMZM2G427557|GRMZM2G427557_T01" length="50" weight="1.000000" />
<sequence id="sequence_216" name="GRMZM2G351977|GRMZM2G351977_T02" length="50" weight="1.000000" />
<sequence id="sequence_217" name="GRMZM2G177386|GRMZM2G177386_T02" length="50" weight="1.000000" />
<sequence id="sequence_218" name="GRMZM2G112728|GRMZM2G112728_T05" length="50" weight="1.000000" />
<sequence id="sequence_219" name="GRMZM2G427531|GRMZM2G427531_T02" length="50" weight="1.000000" />
<sequence id="sequence_220" name="GRMZM2G180720|GRMZM2G180720_T03" length="50" weight="1.000000" />
<sequence id="sequence_221" name="GRMZM2G103103|GRMZM2G103103_T01" length="50" weight="1.000000" />
<sequence id="sequence_222" name="GRMZM2G121494|GRMZM2G121494_T02" length="50" weight="1.000000" />
<sequence id="sequence_223" name="GRMZM2G107089|GRMZM2G107089_T02" length="50" weight="1.000000" />
<sequence id="sequence_224" name="GRMZM2G176840|GRMZM2G176840_T01" length="50" weight="1.000000" />
<sequence id="sequence_225" name="GRMZM2G433002|GRMZM2G433002_T01" length="50" weight="1.000000" />
<sequence id="sequence_226" name="GRMZM2G419244|GRMZM2G419244_T01" length="50" weight="1.000000" />
<sequence id="sequence_227" name="GRMZM2G402092|GRMZM2G402092_T01" length="50" weight="1.000000" />
<sequence id="sequence_228" name="GRMZM2G155216|GRMZM2G155216_T01" length="50" weight="1.000000" />
<sequence id="sequence_229" name="GRMZM2G377855|GRMZM2G377855_T01" length="50" weight="1.000000" />
<sequence id="sequence_230" name="GRMZM2G312910|GRMZM2G312910_T02" length="50" weight="1.000000" />
<sequence id="sequence_231" name="GRMZM2G111216|GRMZM2G111216_T01" length="50" weight="1.000000" />
<sequence id="sequence_232" name="GRMZM2G140809|GRMZM2G140809_T01" length="50" weight="1.000000" />
<sequence id="sequence_233" name="GRMZM2G455413|GRMZM2G455413_T01" length="50" weight="1.000000" />
<sequence id="sequence_234" name="GRMZM2G134130|GRMZM2G134130_T01" length="50" weight="1.000000" />
<sequence id="sequence_235" name="GRMZM2G149428|GRMZM2G149428_T01" length="50" weight="1.000000" />
<sequence id="sequence_236" name="GRMZM2G113033|GRMZM2G113033_T01" length="50" weight="1.000000" />
<sequence id="sequence_237" name="GRMZM2G117572|GRMZM2G117572_T01" length="50" weight="1.000000" />
<sequence id="sequence_238" name="GRMZM2G126361|GRMZM2G126361_T02" length="50" weight="1.000000" />